{
 "title": "opBNB-prerelease.OPGethDetail",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "namespace", "query": "op-bnb-l2-ha-2" },
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "Copied from https://github.com/jsvisa/ethereum-tsdb/blob/main/grafana/provisioning/geth.json"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_header{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Chain Reorg Add",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_add{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Chain Reorg Drop",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_drop{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    },
    {
     "expr": "chain_snapshot_commits{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "gapped nofunds"
    },
    {
     "expr": "rate(txpool_known{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "known"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success RPC QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_success{pod=\"$pod\"}[5m])) by (namespace, pod, method)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure RPC QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_failure{pod=\"$pod\"}[5m])) by (namespace, pod, method)",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(system_cpu_sysload{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "system"
    },
    {
     "expr": "avg(system_cpu_syswait{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(system_cpu_procload{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "geth"
    },
    {
     "expr": "avg(system_cpu_goroutines{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "goroutines"
    },
    {
     "expr": "avg(system_cpu_threads{namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(system_memory_allocs{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "alloc"
    },
    {
     "expr": "system_memory_used{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "used"
    },
    {
     "expr": "system_memory_held{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "held"
    },
    {
     "expr": "system_memory_frees{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "ingress-rate"
    },
    {
     "expr": "rate(p2p_egress{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "egress-rate"
    },
    {
     "expr": "p2p_ingress{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "igress-flow"
    },
    {
     "expr": "p2p_egress{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "egress-flow"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "rate(p2p_dials{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "dials"
    },
    {
     "expr": "rate(p2p_serves{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "serves"
    }
   ]
  },
  {
   "title": "Downloader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throttle",
   "type": "stat",
   "description": "Measured in #peers per second",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(eth_downloader_throttle{namespace=\"$namespace\", pod=~\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eth_downloader_bodies_in{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "bodies in"
    },
    {
     "expr": "rate(eth_downloader_headers_in{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "headers in"
    },
    {
     "expr": "rate(eth_downloader_receipts_in{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "receipts in"
    }
   ]
  },
  {
   "title": "Abnormal QPS",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "eth_downloader_bodies_drop{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "bodies drop"
    },
    {
     "expr": "eth_downloader_headers_drop{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "headers drop"
    },
    {
     "expr": "eth_downloader_receipts_drop{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "receipts drop"
    },
    {
     "expr": "eth_downloader_bodies_timeout{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "bodies timeout"
    },
    {
     "expr": "eth_downloader_headers_timeout{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "headers timeout"
    },
    {
     "expr": "eth_downloader_receipts_timeout{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "receipts timeout"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(eth_downloader_bodies_req{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "bodies(q={{quantile}})"
    },
    {
     "expr": "rate(eth_downloader_headers_req{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "headers(q={{quantile}})"
    },
    {
     "expr": "rate(eth_downloader_receipts_req{namespace=\"$namespace\", pod=~\"$pod\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "receipts(q={{quantile}})"
    }
   ]
  },
  {
   "title": "Fetcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waiting Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_waiting_peers{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Waiting Hashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_waiting_hashes{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Queueing Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_queueing_peers{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Queueing Hashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_queueing_hashes{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Fetching Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_fetching_peers{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Fetching Hashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_fetching_hashes{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "QPS of Transaction",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eth_fetcher_transaction_request_out{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "request out"
    },
    {
     "expr": "rate(eth_fetcher_transaction_request_fail{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "request fail"
    },
    {
     "expr": "rate(eth_fetcher_transaction_request_done{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "request done"
    },
    {
     "expr": "rate(eth_fetcher_transaction_request_timeout{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "request timeout"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_in{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "replies in"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_known{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "replies known"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_underpriced{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "replies underpriced"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_otherreject{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "replies otherreject"
    }
   ]
  },
  {
   "title": "QPS of Block",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eth_fetcher_block_bodies{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "bodies"
    },
    {
     "expr": "rate(eth_fetcher_block_headers{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "headers"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_headers_in{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "filter headers in"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_headers_out{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "filter headers out"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_bodies_in{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "filter bodies in"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_bodies_out{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "filter bodies out"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "ethdb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "ethdb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "ancient write"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_input{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "compact read"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_output{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "compact write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "eth_db_chaindata_disk_write{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "ancient read"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "ancient"
    }
   ]
  },
  {
   "title": "Compact Writedelay Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_compact_writedelay_counter{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Compact",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_compact_time{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "time"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_nonlevel0{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "level0"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_level0{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "~level0"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_memory{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "mem"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_seek{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "seek"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_writedelay_duration{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "delay time"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_writedelay_counter{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "delay count"
    }
   ]
  },
  {
   "title": "Compact Writedelay Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_compact_writedelay_duration{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clean cache-BPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(trie_memcache_clean_write{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Dirty cache-BPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_flush_size{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(trie_memcache_commit_size{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "Clean cache-Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_hit{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_clean_miss{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "miss"
    },
    {
     "expr": "rate(trie_memcache_clean_hit{namespace=\"$namespace\", pod=~\"$pod\"}[1m])/(rate(trie_memcache_clean_miss{namespace=\"$namespace\", pod=~\"$pod\"}[1m])+rate(trie_memcache_clean_hit{namespace=\"$namespace\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "Dirty cache-Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_dirty_hit{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_dirty_miss{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "miss"
    },
    {
     "expr": "rate(trie_memcache_dirty_hit{namespace=\"$namespace\", pod=~\"$pod\"}[1m])/(rate(trie_memcache_dirty_miss{namespace=\"$namespace\", pod=~\"$pod\"}[1m])+rate(trie_memcache_dirty_hit{namespace=\"$namespace\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "MPT-Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_nodes{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_commit_nodes{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(trie_memcache_flush_nodes{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "overflow"
    }
   ]
  },
  {
   "title": "MPT-Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_time{namespace=\"$namespace\", pod=~\"$pod\", quantile=~\"$quantile\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_commit_time{namespace=\"$namespace\", pod=~\"$pod\", quantile=~\"$quantile\"}[1m])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(trie_memcache_flush_time{namespace=\"$namespace\", pod=~\"$pod\", quantile=~\"$quantile\"}[1m])",
     "legendFormat": "overflow"
    }
   ]
  }
 ]
}