{
 "title": "opBNB-ha.OPNode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "op-bnb-l2-ha" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- TODO `op_node_default_refs_number{layer=\"l2\",type=\"received_payload\"}`"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "OP Node Summary ⭐️⭐️⭐️",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Numbers",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by (pod) (op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_unsafe\"})"
    },
    {
     "expr": "max by (pod) (op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_safe\"})"
    },
    {
     "expr": "max by (pod) (op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_finalized\"})"
    }
   ]
  },
  {
   "title": "OP Node L2 ⭐️⭐️⭐️",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Safe Lag ( l2_unsafe - l2_safe ) ⭐️⭐️⭐️",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max by (pod) (op_node_default_refs_number{namespace=\"$namespace\", type=~\"l2_unsafe\",pod=~\"$pod\",layer=\"l2\"}) - max by (pod) (op_node_default_refs_number{namespace=\"$namespace\", type=~\"l2_safe\",pod=~\"$pod\",layer=\"l2\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "L2.Unsafe",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_unsafe\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "L2.Safe",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_safe\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "L2.Finalized",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_finalized\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OP Node SyncStatus.L2 Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "L2.Unsafe Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_unsafe\"}[10m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "L2.Safe Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "rate(op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_safe\"}[10m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "L2.Finalized Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "rate(op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l2\",type=\"l2_finalized\"}[10m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OP Node L1 ⭐️",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "L1 Derived Lag ( l1_head - l1_derived ) ⭐️",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "max by (pod) (op_node_default_refs_number{namespace=\"$namespace\", type=~\"l1_head\",pod=~\"$pod\",layer=\"l1\"}) - max by (pod) (op_node_default_refs_number{namespace=\"$namespace\", type=~\"l1_derived\",pod=~\"$pod\",layer=\"l1\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "L1.Head",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l1\",type=\"l1_head\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "L1.derived",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "op_node_default_refs_number{namespace=~\"$namespace\",pod=~\"$pod\",layer=\"l1\",type=\"l1_derived\"}",
       "legendFormat": "l1_derived.{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}