{
 "title": "opBNB-ha.OPBatcher",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "op-bnb-l2-ha" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Batcher Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Balance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "op_batcher_default_balance{namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Publish Txs Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(op_batcher_default_txmgr_publish_total{namespace=\"$namespace\"}[$interval])",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Batcher Txmgr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending Txs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_pending_txs{namespace=\"$namespace\"}",
     "legendFormat": "pending txs"
    }
   ]
  },
  {
   "title": "Tx Confirmed Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_tx_confirmed_latency_ms{namespace=\"$namespace\"}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Batcher Channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Channel Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "op_batcher_default_input_bytes{namespace=\"$namespace\",stage=\"closed\"}",
     "legendFormat": "channel.input_bytes"
    }
   ]
  },
  {
   "title": "Channel Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "op_batcher_default_output_bytes{namespace=\"$namespace\"}",
     "legendFormat": "channel.output_bytes"
    }
   ]
  },
  {
   "title": "Channel Frames",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "op_batcher_default_channel_num_frames{namespace=\"$namespace\"}",
     "legendFormat": "channel.frames"
    }
   ]
  },
  {
   "title": "Channel Compression Ratio 50%",
   "type": "timeseries",
   "description": "Compression ratios of closed channel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, op_batcher_default_channel_compr_ratio_bucket{namespace=\"$namespace\"})",
     "legendFormat": "channel.compr_ratio"
    }
   ]
  }
 ]
}