{
 "title": "opBNB-ha.OPGethRPCExplorer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "op-bnb-l2-ha" },
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "method",
    "query": "engine_forkchoiceUpdatedV1, engine_getPayloadV1, engine_newPayloadV1, eth_blockNumber, eth_call, eth_chainId, eth_estimateGas, eth_feeHistory, eth_gasPrice, eth_getBalance, eth_getBlockByHash, eth_getBlockByNumber, eth_getLogs, eth_getProof, eth_getTransactionByHash, eth_getTransactionCount, eth_getTransactionReceipt, eth_sendRawTransaction"
   },
   {
    "name": "inteval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RPC $method duration  75%",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rpc_duration_${method}_success{namespace=\"$namespace\",quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPC $method duration  95%",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rpc_duration_${method}_success{namespace=\"$namespace\",quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPC $method duration  99%",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rpc_duration_${method}_success{namespace=\"$namespace\",quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}