{
 "title": "opBNB-ha.OPGeth",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "op-bnb-l2-ha" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OP Geth Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Summary",
     "type": "table",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "chain_head_header{namespace=\"$namespace\", pod=~\"$pod\"}"
      },
      {
       "expr": "chain_head_safe{namespace=\"$namespace\", pod=~\"$pod\"}"
      },
      {
       "expr": "chain_head_finalized{namespace=\"$namespace\", pod=~\"$pod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "OP Geth Header",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Geth Latest",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "chain_head_header{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Geth Safe",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "chain_head_safe{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Geth Finalized",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "chain_head_finalized{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Op Geth RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPC engine_forkchoiceUpdatedV1 duration  75%",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_engine_forkchoiceUpdatedV1_success{namespace=\"$namespace\",quantile=\"0.75\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPC engine_forkchoiceUpdatedV1 duration  95%",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_engine_forkchoiceUpdatedV1_success{namespace=\"$namespace\",quantile=\"0.95\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPC engine_forkchoiceUpdatedV1 duration  99%",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_engine_forkchoiceUpdatedV1_success{namespace=\"$namespace\",quantile=\"0.99\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPC eth_getBlockByNumber duration  75%",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_eth_getBlockByNumber_success{namespace=\"$namespace\",quantile=\"0.75\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPC eth_getBlockByNumber duration  95%",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_eth_getBlockByNumber_success{namespace=\"$namespace\",quantile=\"0.95\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPC eth_getBlockByNumber duration  75%",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_eth_getBlockByNumber_success{namespace=\"$namespace\",quantile=\"0.75\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OP Geth RPC Failure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPC Failure Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "rate(rpc_failure{namespace=\"$namespace\",pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OP Geth TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "TxPool",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "txpool_pending{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "pending.{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}